[project]
name = "prefectx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jake@prefect.io", email = "jake@prefect.io" }
]
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.0.1",
    "prefect>=3.1.13",
    "rich>=13.9.4",
    "typer>=0.13.1",
]

[project.scripts]
prefectx = "prefectx:cli.app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
target-version = "py311"
line-length = 88
fix = true

[tool.ruff.lint]
select = [
    "I",    # isort
    "F",    # pyflakes
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "UP",   # pyupgrade
    "N",    # naming
    "B",    # bugbear
    "A",    # builtins
    "C4",   # comprehensions
    "DTZ",  # datetime
    "T10",  # debugger
    "ERA",  # eradicate
    "RET",  # return
    "SLF",  # self
    "RUF",  # ruff-specific rules
]

[tool.ruff.lint.isort]
known-first-party = ["prefect"]
combine-as-imports = true
relative-imports-order = "closest-to-furthest"